### ISSUE TITLE
Errors on startup

### ISSUE THREAD

**Issue by olijeffers0n** [1lolplayer1/IDE-A#1]
```
This is a beta version
report any bugs to https://github.com/1lolplayer1/IDE-A
lmao
Traceback (most recent call last):
  File "A:\Downloads\IDE-A-main\IDE-A-main\src\New_UI_windows.py", line 274, in <module>
    cdg.prog = re.compile(r'\b(?P<MYGROUP>tkinter)\b|' + ic.make_pat(), re.S)
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "re.Pattern") to str
```

Error on launch, does not get past this

**Comment by SquidsHub** [comment]
> ```
> 
> This is a beta version
> 
> report any bugs to https://github.com/1lolplayer1/IDE-A
> 
> lmao
> 
> Traceback (most recent call last):
> 
>   File "A:\Downloads\IDE-A-main\IDE-A-main\src\New_UI_windows.py", line 274, in <module>
> 
>     cdg.prog = re.compile(r'\b(?P<MYGROUP>tkinter)\b|' + ic.make_pat(), re.S)
> 
>                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
> 
> TypeError: can only concatenate str (not "re.Pattern") to str
> 
> ```
> 
> 
> 
> Error on launch, does not get past this


This issue has bin fixed!

**Comment by SquidsHub** [comment]
Put me as a contributor. It's me Squids
